### ISSUE TITLE
Namespace Error: Only components in the same namespace as the organization can be created through the API

### ISSUE THREAD

**Issue by mubeen-qawi** [haripriyamurthy/CustomMetadataLoader#10] opened 2016-09-09 05:49 UTC
Cannot create a new component with the namespace: hortonworks. Only components in the same namespace as the organization can be created through the API

Do you know what is the problem here. I think it should be a straight forward fix

**Comment by mikeconroy** [comment] 2016-09-12 13:29
This is a duplicate of [this issue](https://github.com/haripriyamurthy/CustomMetadataLoader/issues/4).
It was solved by manually creating the remote site settings in the setup.

**Closed as completed** 2016-09-12 17:38 UTC

**Comment by sjurgis** [comment] 2019-01-06 22:41
Note this error happens when you have two consequent underscores - hence API interprets this as Namespace rather than record name.
